name: 'QMS generate verification report'
description: 'Generates a verification report based on pipeline metadata and test results as inputs.'
inputs:
  testresults_artifact:
    required: true
    description: 'Artifact name of files uploaded of previously generated test results during runs of (IV, PV) or (pIV, pPV), e.g. [testresults-validation, testresults-production].'
    default: ''
  repository_artifact:
    required: true
    description: 'Artifact name of the repository being tested: it will almost always be the triggering branch and repository of the workflow calling this action.'
    default: ''
  ready_for:
    required: true
    description: 'Indicates whether the verification report is generated for the validation or production environment with respective possible values: [production, use].'
    default: ''
  feature_files_path:
    required: true
    description: 'Path to the directory containing the feature files (.feature). Subfolders within is supported. Relative to the root of the provided repository.'
    default: ''
  system_design_specification_path:
    required: true
    description: 'Path to the directory containing the system design specifications files (.md). Subfolders within is supported. Relative to the root of the provided repository.'
    default: ''
  system_configuration_specification_path:
    required: true
    description: 'Path to the directory containing the system configuration specifications files (.md). Subfolders within is supported. Relative to the root of the provided repository.'
    default: ''
  it_solution_name:
    required: true
    description: 'Name of the IT solution. This will be in the verification report.'
    default: ''
  project_name:
    required: true
    description: 'Name of the project. This will be in the verification report.'
    default: ''
  environment_name:
    required: true
    description: 'Name of the environment. This will be in the verification report.'
    default: ''
  github_token:
    required: true
    description: 'GitHub token to use for API access.'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      with:
        repository: nn-dma/generate-verification-report
        path: .

    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: 1.23.3
        cache: false

    # Note: v4 is currently used but is not yet fully supported in GitHub Enterprise Server
    - name: Download repository
      uses: actions/download-artifact@v4.1.8
      with:
        name: ${{ inputs.repository_artifact }}
        path: input/repository

    # Note: v4 is currently used but is not yet fully supported in GitHub Enterprise Server
    - name: Download test results
      uses: actions/download-artifact@v4.1.8
      with:
        name: ${{ inputs.testresults_artifact }}
        path: input/testresults

    # TODO: Read and inject other parameter values into 'parameters.json' in the /input directory

    - name: Run other tests (dev debug)
      shell: bash
      run: |
        echo "Test results artifact name: ${{ inputs.testresults_artifact }}"
        echo "Ready for: ${{ inputs.ready_for }}"
        echo "Current directory: $(pwd)"
        echo "Repository directory:"
        ls -la input/repository
        echo "Test results directory:"
        ls -la input/testresults
        echo "Current:"
        ls -la
        echo ""
        echo "Parent:"
        ls -la ../
        echo ""
        echo "Grandparent:"
        ls -la ../../

    - name: Inject parameter values
      shell: bash
      run: |
        cat <<< "$(jq --indent 4 '.ready_for = "${{ inputs.ready_for }}"' input/parameters.json)" > input/parameters.json
        cat <<< "$(jq --indent 4 '.feature_files_path = "${{ inputs.feature_files_path }}"' input/parameters.json)" > input/parameters.json
        cat <<< "$(jq --indent 4 '.system_configuration_specification_path = "${{ inputs.system_configuration_specification_path }}"' input/parameters.json)" > input/parameters.json
        cat <<< "$(jq --indent 4 '.system_design_specification_path = "${{ inputs.system_design_specification_path }}"' input/parameters.json)" > input/parameters.json
        cat <<< "$(jq --indent 4 '.it_solution_name = "${{ inputs.it_solution_name }}"' input/parameters.json)" > input/parameters.json
        cat <<< "$(jq --indent 4 '.project_name = "${{ inputs.project_name }}"' input/parameters.json)" > input/parameters.json
        cat <<< "$(jq --indent 4 '.environment_name = "${{ inputs.environment_name }}"' input/parameters.json)" > input/parameters.json
        cat <<< "$(jq --indent 4 --arg grid "$GITHUB_RUN_ID" '.pipeline_run_id = $grid' input/parameters.json)" > input/parameters.json

    - name: Generate verification report
      uses: dagger/dagger-for-github@v6.8.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        verb: run
        args: go run -C src main.go
        version: "0.14.0"

    - name: Print logs
      shell: bash
      if: always()
      run: cat src/run.log

    - name: Generate verification report filename
      shell: bash
      run: |
        verification_report_filename=$(src/script/get_verification_report_filename_for_context.sh $(jq -r '.environment_name' < input/parameters.json) $(jq -r '.pipeline_run_id' < input/parameters.json) ${{ inputs.ready_for }}).html
        echo "$verification_report_filename"
        echo "verification_report_filename=$verification_report_filename" >> $GITHUB_ENV

    - name: Generate verification report artifact name
      shell: bash
      run: |
        verification_report_artifact_name=$(src/script/get_verification_report_artifact_name_for_context.sh ${{ inputs.ready_for }})
        echo "$verification_report_artifact_name"
        echo "verification_report_artifact_name=$verification_report_artifact_name" >> $GITHUB_ENV

    - name: Upload verification report
      uses: actions/upload-artifact@v4.4.0
      with:
        name: ${{ env.verification_report_artifact_name }}
        path: output/${{ env.verification_report_filename }}
