name: Dagger workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Dagger workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6
          cache: false

      - name: Run Dagger workflow
        run: dagger run go run main.go
        working-directory: src
