name: Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.7
          cache: false

      # - name: Install Go module dependencies
      #   run: go mod download
      #   working-directory: src

      # - name: Run Dagger workflow
      #   run: dagger run go run main.go
      #   working-directory: src

      - name: Run integration tests
        uses: dagger/dagger-for-github@v5
        with:
          workdir: src
          verb: run
          args: go run main.go
          version: "0.9.9"

      - name: Test that output report file is generated and not empty
        run: |
          if [ $(wc -c < "output/report.html") -eq 0 ]; then
          exit 1
          fi

