name: Unit Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: 1.25.3
          cache: false

      - name: Run unit tests
        run: go test -C test/unit -v
