name: Integration Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Checkout report testing repository
        uses: actions/checkout@v4.1.7
        with:
          repository: NovoNordisk-OpenSource/generate-verification-report-test
          path: input/repository
          fetch-depth: 0
          fetch-tags: true

      - name: Prepare test results
        run: |
          mkdir -p input/testresults
          cp -r test/unit/data/allure-pytest/valid/* input/testresults

      - name: Set up Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: 1.25.3
          cache: false

      - name: Test Dagger workflow
        uses: dagger/dagger-for-github@v8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OVERRIDE_GITHUB_SHA: 857f21d4180b60ad12978b14db0e6a3e191f8ec0
        with:
          verb: run
          args: go run -C src main.go
          version: "0.19.3"

      - name: Print logs
        if: always()
        run: cat src/run.log

      - name: Run integration tests
        run: go test -C test/integration -v

