name: GitHub Action Tests

on:
  push:
    branches:
      - main
  
jobs:
  init:
    name: Checkout repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  generate_verification_report:
    name: Generate verification report using GitHub Action
    runs-on: ubuntu-latest
    steps:
      - uses: nn-dma/generate-verification-report@main
        with:
          test: testinputsforverificationreport
          ready_for: production