name: Integration Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout report testing repository
        uses: actions/checkout@v4
        with:
          repository: nn-dma/generate-verification-report-test
          path: input/repository
          fetch-depth: 0
          fetch-tags: true

      - name: Prepare test results
        run: |
          mkdir -p input/testresults
          cp -r test/unit/data/allure-pytest/valid/* input/testresults

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
          cache: false

      - name: Test Dagger workflow
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run -C src main.go
          version: "0.11.1"

      - name: Print logs
        if: always()
        run: cat src/run.log

      - name: Run integration tests
        run: go test -C test/integration -v

