name: GitHub Action Tests

on:
  push:
    branches:
      - main
  
jobs:
  init:
    name: Initialize test environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload sample test results
        uses: actions/upload-artifact@v3
        with:
          name: testresults-validation
          path: test/unit/data/allure-pytest/valid

  generate_verification_report:
    name: Generate verification report using GitHub Action
    runs-on: ubuntu-latest
    steps:
      - uses: nn-dma/generate-verification-report@main
        with:
          testresults_artifact_name: testresults-validation
          ready_for: production