name: GitHub Action Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  init:
    name: Initialize test environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action repository
        uses: actions/checkout@v4
      - name: Checkout report testing repository
        uses: actions/checkout@v4
        with:
          repository: nn-dma/generate-verification-report-test
          path: input/repository
          fetch-depth: 0
          fetch-tags: true
      - name: Upload sample repository
        uses: actions/upload-artifact@v3
        with:
          name: repository
          path: input/repository
      - name: Upload sample test results
        uses: actions/upload-artifact@v3
        with:
          name: testresults-validation
          path: test/unit/data/allure-pytest/valid

  # TODO: Inject the entire repository being tested as a parameter
  generate_verification_report:
    name: Generate verification report using GitHub Action
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: nn-dma/generate-verification-report@main
        with:
          testresults_artifact: testresults-validation
          repository_artifact: repository
          ready_for: production