name: Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
          cache: false

      - name: Test Dagger workflow
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run -C src main.go
          version: "0.10.2"

      - name: Print logs
        if: always()
        run: cat src/run.log

      - name: Run integration tests
        run: go test -C test/integration -v

