name: GitHub Action Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
  
jobs:
  init:
    name: Initialize test environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action repository
        uses: actions/checkout@v4
      - name: Checkout report testing repository
        uses: actions/checkout@v4
        with:
          repository: nn-dma/generate-verification-report-test
          path: input/repository
          fetch-depth: 0
          fetch-tags: true
      - name: Upload sample repository
        uses: actions/upload-artifact@v4
        with:
          name: repository
          path: input/repository
      - name: Upload sample test results
        uses: actions/upload-artifact@v4
        with:
          name: testresults-validation
          path: test/unit/data/allure-pytest/valid
      # - name: Inject context values
      #   shell: bash
      #   run: |
      #     echo "Injecting context values:"
      #     echo "GITHUB_REPOSITORY=nn-dma/generate-verification-report-test" >> $GITHUB_ENV
      #     echo "GITHUB_REF_NAME=main" >> $GITHUB_ENV
      #     echo "GITHUB_SHA=061830180fd30a302441b6f87e149a0ab9571829" >> $GITHUB_ENV
      #     echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
      #     echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
      #     echo "GITHUB_SHA=$GITHUB_SHA"

  generate_verification_report:
    name: Generate verification report using GitHub Action
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Inject context values
        shell: bash
        run: |
          echo "Injecting context values:"
          export GITHUB_REPOSITORY=nn-dma/generate-verification-report-test
          export GITHUB_REF_NAME=main
          export GITHUB_SHA=061830180fd30a302441b6f87e149a0ab9571829
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_SHA=$GITHUB_SHA"
      - uses: nn-dma/generate-verification-report@main
        with:
          testresults_artifact: testresults-validation
          repository_artifact: repository
          feature_files_path: requirements
          system_configuration_specification_path: docs/configuration
          system_design_specification_path: docs/design
          it_solution_name: "Sample IT Solution"
          project_name: "Sample Project"
          environment_name: "sample-environment"
          ready_for: use